---

name: ingest organisations from Bushfire Directory
spreadsheet_key: 1UflHns4xANQ9lo4c9N1CdSNF58HBrFh-g99eDhRQrcQ
worksheets:
- name: Accomm
  category: Accomodation
- name: Animals
  category: Animals
schema_mapping:
  'title': 'Organisation/group name'
  'categories[0]': '__CATEGORY'
  'categories[1]': 'Sub-category 1'
