---

name: ingest organisations from Bushfire Directory
spreadsheet_key: '1WyteykN-L_yZwS6jVNY0tb-CVWNtYBaGkxYKxJaEDRM'
skip_rows: 6
worksheets:
- name: 'Accommodation'
- name: 'Pets, livestock and wildlife'
- name: 'Goods/supplies donations'
- name: 'Money donations'
- name: 'Local community groups '
  category: Local community groups
- name: 'General assistance or information'
schema_mapping:
  'title': 'Organisation/group name'
  'category': '__CATEGORY'
  'category_sub': 'Sub-category 1'
  'category_sub_sub': 'Sub-category 2'
  'location': 'State/Territory'
  'lga': 'LGA'
  'description': 'Brief description'
  # 'Contact name'
  'phone': 'Contact number'
  'email': 'Contact email'
  'address': 'Contact address'
  'link': 'Link'
  # 'Operating hours'
