---

name: ingest organisations from Bushfire Directory for dev
spreadsheet_key: '18OkKv06YwJxOiRZuX2pIxmRWxE3rBjECtJ0pL-DL_m0'
skip_rows: 0
worksheets:
- name: 'MAIN SHEET DATA - DO NOT CHANGE'
taxonomy_fields:
- "What is the nature of your offer or request?"
- "Sub-category 1"
- "Sub-category 2"
taxonomy:
  1: "Housing / Accommodation (Human)"
  6: "Pets / Livestock / Wildlife"
  11: "Fundraising / Donations / Volunteers"
  21: "Health / Medical / First Aid"
  26: "Boarding / Agistment"
  31: "Transportation"
  36: "Veterinary care"
  41: "Wildlife Supplies"
  76: "Online donations"
  81: "Drop-off location"
  86: "Pick-up location"
  91: "Money Donations"
  147: "lessons-learnt"
  148: "crisis-planning"
  151: "Financial / Insurance"
  152: "Government / Legal"
  153: "Power / Telecommunications"
  154: "Other"
  174: "resilience"
  175: "Weather / Road Conditions"
  176: "General Emergency Topics (incl. relief and recovery)"
  177: "Recovery / Reconstruction"
  178: "Dogs"
  179: "Cats"
  180: "Horses"
  181: "Livestock / Large Animals"
  182: "Wildlife / Other Animals"
  183: "Food / Water"
  184: "Clothing / Shoes"
  185: "Toiletries / Personal Care"
  186: "Generators / Batteries / Power"
  187: "Fuel / EV Charging"
  188: "Transportation"
  189: "Phone / Internet"
  190: "Trades"
  191: "Cleaning ups / Building"
  192: "Packing / Delivery"
  193: "Goods / Services"
  208: "Books"
  209: "Mental Health"
  211: "Music / Instruments"
  212: "Information"
  213: "Community support"
  214: "Donations drop-off"
  215: "Emergency Alerts / Safety Information"
  216: "Employment and businesses"
  217: "Evacuation Centres"
  218: "Facebook community group"
  219: "Financial and banking"
  220: "Grants / Scholarships"
  221: "Information Topics"
  222: "Local community group"
  223: "Pick-up and delivery"
  224: "COVID-19"
  225: "Feed"
  226: "Medical"
  228: "Other Pets / Small Domestic Animals"
  229: "Renters and housing"
  230: "Restaurants"
  231: "Reunification / Finding People"
  232: "Schools and education"
  233: "Seeking Volunteers"
  234: "Supermarkets"
  235: "Telecommunications"
  236: "Testing Clinic"
  237: "Travel advice"
  238: "Donation Details"
  239: "Campervans"
