name: Lint, Test and Ingest

on:
  push:
  repository_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        make install_reqs_dev
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Save creds
      run: |
        echo $'${{ secrets.GOOGLE_CREDS }}' | base64 -d > crisisapp-264723-d73f4f94e829.json
    - name: Ingest
      run: |
        python -m ingestion.core --creds-file crisisapp-264723-d73f4f94e829.json --output-file organisations.json
    - name: Copy via ssh
      uses: garygrossgarten/github-action-scp@v0.5.3
      if: github.ref == 'refs/heads/master'
      with:
        local: organisations.json
        remote: /var/www/crisis.app/json/organisations.json
        host: crisis.app
        username: ${{ secrets.FTP_USERNAME }}
        privateKey: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        passphrase: ${{ secrets. DEPLOY_KEY_PASSWORD }}
